wordpress:
  wordpressPassword: foo
  mariadb:
    db:
      password: bar
    rootUser:
      password: baz
  ingress:
    enabled: true
    certManager: true
    hostname: wordpress-chart.devops-space.pp.ua
    annotations: {
      kubernetes.io/ingress.class: nginx,
      cert-manager.io/cluster-issuer: letsencrypt-prod
    }
    extraTls:
    - hosts:
      - wordpress-chart.devops-space.pp.ua
      secretName: wordpress-chart.devops-space.pp.ua
