on:
  push:
    paths:
      - '.github/workflows/httperf.yaml'
    branches:
      - master
jobs:
  docker:
    runs-on: ubuntu-latest
    name: httperf
    steps:
    - name: run-httperf
      using: 'docker'
      image: 'docker://dos65/httperf:latest'
      env:
        SERVER: "bstock.com"
        NUM-CONNS: "20"
